# Generated by Django 3.2.7 on 2022-03-28 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_family', models.TextField(max_length=300)),
                ('date', models.DateField(default=None, null=True, verbose_name='Дата')),
                ('phone_number', models.CharField(max_length=20)),
                ('school_type', models.CharField(choices=[('elementary', 'Начальная школа'), ('middle', 'Средняя школа'), ('high', 'Старшая школа')], default='elementary', max_length=50)),
                ('grade', models.PositiveSmallIntegerField()),
                ('pay', models.CharField(max_length=20)),
                ('registered', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('extra_classes', models.CharField(max_length=500)),
                ('additional_info', models.CharField(max_length=500)),
                ('father_name', models.TextField(max_length=300)),
                ('father_phone', models.CharField(max_length=20)),
                ('father_job', models.CharField(max_length=50)),
                ('mother_name', models.TextField(max_length=300)),
                ('mother_phone', models.CharField(max_length=20)),
                ('mother_job', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
